apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-config
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/piomin/argocd-showcase.git
              revision: HEAD
              directories:
                - path: projects/*
          - list:
              elements:
                - env: test
                - env: uat
                - env: prod
  template:
    metadata:
      name: '{{.path.basename}}-{{.env}}-config'
    spec:
      destination:
        namespace: '{{.path.basename}}-{{.env}}'
        server: 'https://kubernetes.default.svc'
      project: default
      sources:
        - path: chart
          repoURL: 'https://github.com/piomin/argocd-showcase.git'
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/projects/{{.path.basename}}/values-{{.env}}.yaml
              - $values/projects/{{.path.basename}}/values.yaml
            parameters:
              - name: name
                value: '{{.path.basename}}-{{.env}}'
        - repoURL: 'https://github.com/piomin/argocd-showcase.git'
          targetRevision: HEAD
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true