apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: {{ .Values.name }}
spec:
  hard:
    pods: {{ (.Values.quotas).pods | default "10" }}
    requests.cpu: {{ (.Values.quotas).cpuRequest | default "2" }}
    requests.memory: {{ (.Values.quotas).memoryRequest | default "2Gi" }}
    limits.cpu: {{ (.Values.quotas).cpuLimit | default "8" }}
    limits.memory: {{ (.Values.quotas).memoryLimit | default "8Gi" }}